/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedPropertiesRouteImport } from './routes/_authenticated/properties'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminBookingsRouteImport } from './routes/_authenticated/admin/bookings'
import { Route as ApiPublicBookingsRouteImport } from './routes/api/public/bookings'
import { Route as ApiPublicPropertiesSearchRouteImport } from './routes/api/public/properties/search'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPropertiesRoute = AuthenticatedPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminBookingsRoute =
  AuthenticatedAdminBookingsRouteImport.update({
    id: '/admin/bookings',
    path: '/admin/bookings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicBookingsRoute = ApiPublicBookingsRouteImport.update({
  id: '/api/public/bookings',
  path: '/api/public/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPropertiesSearchRoute =
  ApiPublicPropertiesSearchRouteImport.update({
    id: '/api/public/properties/search',
    path: '/api/public/properties/search',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/properties': typeof AuthenticatedPropertiesRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/api/public/bookings': typeof ApiPublicBookingsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/properties/search': typeof ApiPublicPropertiesSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/properties': typeof AuthenticatedPropertiesRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/api/public/bookings': typeof ApiPublicBookingsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/properties/search': typeof ApiPublicPropertiesSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRoute
  '/_authenticated/properties': typeof AuthenticatedPropertiesRoute
  '/_authenticated/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/api/public/bookings': typeof ApiPublicBookingsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/properties/search': typeof ApiPublicPropertiesSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bookings'
    | '/properties'
    | '/admin/bookings'
    | '/api/public/bookings'
    | '/admin/'
    | '/api/public/properties/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bookings'
    | '/properties'
    | '/admin/bookings'
    | '/api/public/bookings'
    | '/admin'
    | '/api/public/properties/search'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/bookings'
    | '/_authenticated/properties'
    | '/_authenticated/admin/bookings'
    | '/api/public/bookings'
    | '/_authenticated/admin/'
    | '/api/public/properties/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicBookingsRoute: typeof ApiPublicBookingsRoute
  ApiPublicPropertiesSearchRoute: typeof ApiPublicPropertiesSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties': {
      id: '/_authenticated/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof AuthenticatedPropertiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/bookings': {
      id: '/_authenticated/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AuthenticatedAdminBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/bookings': {
      id: '/api/public/bookings'
      path: '/api/public/bookings'
      fullPath: '/api/public/bookings'
      preLoaderRoute: typeof ApiPublicBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/properties/search': {
      id: '/api/public/properties/search'
      path: '/api/public/properties/search'
      fullPath: '/api/public/properties/search'
      preLoaderRoute: typeof ApiPublicPropertiesSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRoute
  AuthenticatedPropertiesRoute: typeof AuthenticatedPropertiesRoute
  AuthenticatedAdminBookingsRoute: typeof AuthenticatedAdminBookingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBookingsRoute: AuthenticatedBookingsRoute,
  AuthenticatedPropertiesRoute: AuthenticatedPropertiesRoute,
  AuthenticatedAdminBookingsRoute: AuthenticatedAdminBookingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicBookingsRoute: ApiPublicBookingsRoute,
  ApiPublicPropertiesSearchRoute: ApiPublicPropertiesSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
